let header_for_PC = '<div class="col l-2 c-1 m-1 logo" id="logocontainer">'
+'<a href="#">'
+    '<img src="views/img/logo-no-background.png" alt="">'
+'</a>'
+'</div>'
+'<div class="col l-10 c-11 m-11" id="logocontainer">'
+    '<div class="notifi_container">'

+    '</div>'
+'</div>';
let header_for_mobile_tablet = '<!-- Logo Col -->'
+'<div class="col l-2 c-2 m-2" style="padding: 0;">'
+'<div class="col l-12 c-12 m-12 logo" id="logocontainer">'
    +'<a href="#">'
    +   '<img src="views/img/cloudroom-favicon-color.png" alt="">'    
    +'</a>'
+'</div>'
    +'<div id="sidebarbuttoncontainermoile" class="col l-0 c-12 m-12" style="padding: 0; width: 100%;">'
    +    '<button class="side-bar-button" onclick="SidebarButtonOpenformobile()" style="width: 100%; margin: 5px 0px 1px 0px;">'
    +        '<span class="material-symbols-outlined">'
    +            'arrow_drop_down'
    +        '</span>'
    +    '</button>'
    +'</div>'
+   '</div>'
+ '<!-- Notifi Col -->'
+'<div class="col l-10 c-10 m-10">'
+    '<div class="notifi_container">'

+    '</div>'
+'</div>';
let main_for_PC = '<!-- Sidebar Container -->'
+'<div class="col l-2 c-0 m-0" style="padding: 0;">'
    +'<div class="col l-12 c-0 m-0" style="padding: 0;" id="sidebarbuttoncontainer">'
        +'<button class="side-bar-button" onclick="SidebarButtonHide()">'
            +'<span class="material-symbols-outlined">'
            +    'arrow_drop_up'
            +'</span>'
        +'</button>'
    +'</div>'
    +'<!-- Side bar -->'
    +'<ul id="sidebar" class="side-bar">'
        +'<li>'
            +'<button>Home</button>'
        +'</li>'
        +'<li>'
            +'<button>Profile</button>'
        +'</li>'
        +'<li>'
            +'<button>Post Question</button>'
        +'</li>'
        +'<li>'
            +'<button>Settings</button>'
        +'</li>'
        +'<li>'
            +'<button>Community</button>'
        +'</li>'
    +'</ul>'
+'</div>'
+'<!-- Content Col -->'
+'<div class="col l-10 c-12 m-12">'
    +'<!-- Content container -->'
    +'<div class="container-content">'
        
    +'</div>'
+'</div>';
let main_for_mobile_tablet = '<!-- Sidebar Container -->'
+'<div id="sidebarcontainermobile" class="col l-2 c-12 m-12" style="padding: 0; position:absolute; display:none;">'
+      '<div class="col l-12 c-12 m-12" style="padding: 0;">'
            +'<!-- Side bar -->'
            +'<ul id="sidebar" class="side-bar">'
                +'<li>'
                    +'<button>Home</button>'
                +'</li>'
                +'<li>'
                    +'<button>Profile</button>'
                +'</li>'
                +'<li>'
                    +'<button>Post Question</button>'
                +'</li>'
                +'<li>'
                    +'<button>Settings</button>'
                +'</li>'
                +'<li>'
                    +'<button>Community</button>'
                +'</li>'
            +'</ul>'
+      '</div>'
+'</div>'
+'<!-- Content Col -->'
+'<div class="col l-10 c-12 m-12" style="padding-left: 0;">'
    +'<!-- Content container -->'
    +'<div class="container-content">'
        
    +'</div>'
+'</div>';